production:
  access_key_id: ENV['S3_ACCESS_KEY']
  secret_access_key: ENV['S3_SECRET_KEY']
  bucket: ENV['S3_BUCKET_NAME']
  folder:
  endpoint:
  secure:
  private:
  expires:
  proxy:
  thumb_folder:

development:
  access_key_id:
  secret_access_key:
  bucket:
  folder:
  endpoint:
  secure:
  private:
  expires:
  proxy:
  thumb_folder:

# Uncomment this to run plugin tests with standart redmine script
# test:
#   access_key_id:
#   secret_access_key:
#   bucket:
