production:
  access_key_id: 'AKIAI4JJYM272ZDANFJQ'
  secret_access_key: '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'
  bucket: 'ehc.delivery.data'
  endpoint: 's3-ap-southeast-1.amazonaws.com'

staging:
  access_key_id: 'AKIAI4JJYM272ZDANFJQ'
  secret_access_key: '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'
  bucket: 'ehc.dev-delivery'
  endpoint: 's3-ap-southeast-1.amazonaws.com'

# Uncomment this to run plugin tests with standart redmine script
# test:
#   access_key_id:
#   secret_access_key:
#   bucket:

